Update banks.py
cuenca-mx/clabe-python pull request #94
Opened 2022-02-07 18:57 UTC by xabiArcus

Added Arcus as participant of the SPEI network

2022-02-07 19:10 UTC, matin requested changes

2022-02-07 19:10 UTC, matin commented on clabe/banks.py
> +    '706':'90706',
missing a space to pass lint

2022-02-07 19:21 UTC, xabiArcus commented on clabe/banks.py
> +    '706':'90706',
ok!

2022-08-17 20:43 UTC, felipaoo approved these changes

2022-08-17 20:44 UTC, merged

2022-08-17 20:44 UTC, felipaoo commented
thanks @xabiArcus !